# Generated by Django 4.1.7 on 2023-04-05 19:46

from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_drf_filepond", "0010_temp_chunked_biginteger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryupload",
            name="file",
            field=models.FileField(
                storage=django_drf_filepond.models.TemporaryS3Storage(),
                upload_to=django_drf_filepond.models.get_upload_path,
            ),
        ),
    ]
