# Generated by Django 4.1.7 on 2023-04-05 22:44

from django.db import migrations, models
import django_drf_filepond.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_drf_filepond", "0011_alter_temporaryupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedupload",
            name="file",
            field=models.FileField(
                max_length=2048,
                storage=django_drf_filepond.models.PermanentS3Storage(),
                upload_to="",
            ),
        ),
    ]
