# Generated by Django 4.1.7 on 2023-04-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_filepond', '0012_alter_storedupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedupload',
            name='file_type',
            field=models.TextField(choices=[('jpeg', 'jpeg'), ('jpg', 'jpg'), ('png', 'png'), ('heic', 'heic'), ('mp4', 'mp4'), ('webp', 'webp'), ('webm', 'webm')], default='jpeg', max_length=50),
        ),
    ]
